# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=200)),
                ('offer_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
