# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_auto_20160705_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='current',
            name='product_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
