# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_current_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='current',
            name='vendor_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
