# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0006_current_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='current',
            old_name='client',
            new_name='clientname',
        ),
        migrations.AddField(
            model_name='current',
            name='clientnnum',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
