# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0008_auto_20160726_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='current',
            name='offernum',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
